[package]
name = "cargo-risczero"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "RISC Zero CLI tools"
readme = "README.md"
keywords = ["risc0", "risczero", "tool", "cli", "generate"]

[[bin]]
name = "r0vm"
doc = false

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
cargo-generate = { version = "0.19", features = ["vendored-openssl"] }
cargo_metadata = { version = "0.18", optional = true }
clap = { version = "4", features = ["derive"] }
const_format = "0.2"
dirs = "5.0"
downloader = { version = "0.2", default-features = false, features = [
  "rustls-tls",
] }
flate2 = "1"
fs2 = "0.4"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
reqwest-middleware = "0.2"
reqwest-retry = "0.3"
risc0-build = { workspace = true }
risc0-r0vm = { workspace = true, optional = true }
risc0-zkvm = { workspace = true, optional = true }
serde = { version = "1", features = ["derive"] }
syn = "2.0.38"
tar = "0.4"
tempfile = "3"
text_io = "0.1.12"
tokio = { version = "1", features = ["rt"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zip = { version = "0.6", optional = true }

[build-dependencies]
risc0-build = { workspace = true, optional = true }
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
], optional = true }
zip = { version = "0.6", optional = true }

[features]
cuda = ["risc0-zkvm/cuda"]
default = ["r0vm"]
docker = []
experimental = [
  "dep:cargo_metadata",
  "dep:tracing-subscriber",
  "dep:risc0-build",
  "dep:zip",
  "risc0-zkvm/prove",
]
metal = ["risc0-zkvm/metal"]
r0vm = ["dep:risc0-r0vm"]
